  workflows:
    sample-workflow:
      environment:
        android_signing:
          - ~/.android/app/upload-keystore.jks

        flutter: stable
      name: Codemagic Sample Workflow
      max_build_duration: 120
      instance_type: mac_mini_m1
    android-workflow-id:
      name: Android Sample Workflow

  scripts:
    - name: Set up local.properties
      script: |
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    - name: Get Flutter packages
      script: |
        flutter packages pub get
    - name: Build AAB with Flutter
      script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
        flutter build appbundle --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER
    - artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log